version: '3.4'

services:
  frontendservice:
    image: frontendservice
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 5010:5010
      - 9229:9229
    command: ["node", "--inspect=0.0.0.0:9229", "index.js"]
